name: hashdeep
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        sh bootstrap.sh
        ./configure
        make
        sudo make install
    - uses: actions/upload-artifact@v4
      with:
        name: hashdeep
        path: |
          /usr/local/bin/hashdeep
          /usr/local/bin/md5deep
          /usr/local/bin/sha1deep
          /usr/local/bin/sha256deep
          /usr/local/bin/whirlpooldeep
          /usr/local/bin/tigerdeep
  build-windows:
      runs-on: windows-2019
      steps:
      - uses: actions/checkout@v4
      - name: Setup MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          version: 12.2.0
      - name: Build
        run: |
          sh bootstrap.sh
          ./configure
          make
          make install
